const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const INCREASE_PRODUCT = 'INCREASE_PRODUCT';
const DECREASE_PRODUCT = 'DECREASE_PRODUCT';
const CART_EMPTY = 'CART_EMPTY';
const CHECKOUT = 'CHECKOUT';

export {
    ADD_TO_CART,
    REMOVE_FROM_CART,
    INCREASE_PRODUCT,
    DECREASE_PRODUCT,
    CART_EMPTY,
    CHECKOUT
}